
spring.application.name=job-service

spring.datasource.url=jdbc:mysql://localhost:3306/job_platform
spring.datasource.username=root
spring.datasource.password=ARammy1926

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379 
