spring.application.name=api-gateway

server.port=${PORT:8081}

# Job Service route
spring.cloud.gateway.server.webflux.routes[0].id=job-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://${JOB_SERVICE_HOST:localhost}:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/jobs/**

# Authentication route
spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://${JOB_SERVICE_HOST:localhost}:8080
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/auth/**